// Cinema data — documentaries, films, performance recordings, podcasts,
// series, and talks for the AAC Cinema.
//
// isFree: true  → url points to legal free access; shown with a FREE ★ badge
// isFree: false → show platform + howToAccess instructions instead
// isEssential   → highlighted as a top pick in the UI
// hasAD / hasCaptions → known accessible versions exist

export type CinemaItemType =
  | 'documentary'
  | 'performance-recording'
  | 'short-film'
  | 'podcast'
  | 'series'
  | 'film'
  | 'talk'
  | 'video-essay';

export type CinemaItem = {
  slug: string;
  title: string;
  director?: string;       // for films and docs
  creator?: string;        // for podcasts and series
  year?: number;
  description: string;
  url?: string;            // legal free-access URL (only when isFree: true)
  type: CinemaItemType;
  category: string;        // matches a CinemaCategory id
  tags: string[];
  isFree: boolean;
  platform?: string[];     // e.g. ['Netflix'], ['YouTube'], ['PBS'], ['Podcast']
  howToAccess?: string;    // for non-free items
  isEssential?: boolean;
  runtimeMinutes?: number;
  hasAD?: boolean;
  hasCaptions?: boolean;
};

export type CinemaCategory = {
  id: string;
  channel: string;   // two-digit channel number
  call: string;      // four-letter call sign
  title: string;
  description: string;
};

export const CINEMA_CATEGORIES: CinemaCategory[] = [
  { id: 'documentaries',    channel: '01', call: 'DOCS', title: 'Documentaries',              description: 'Feature documentaries on disability culture, rights history, and community life.' },
  { id: 'performance',      channel: '02', call: 'PERF', title: 'Performance & Dance',         description: 'Recorded live performances, dance films, and theater from disabled and Deaf artists.' },
  { id: 'short-film',       channel: '03', call: 'SHRT', title: 'Short Films & Video Art',     description: 'Short films, video essays, and arts media — many freely streamable.' },
  { id: 'podcasts',         channel: '04', call: 'CAST', title: 'Podcasts & Audio',            description: 'Essential listening: disability culture, arts, and community — all free to stream.' },
  { id: 'series-tv',        channel: '05', call: 'SERS', title: 'Series & Television',         description: 'Notable TV series with disabled characters, Deaf representation, or disability arts focus.' },
  { id: 'narrative-film',   channel: '06', call: 'DRAM', title: 'Narrative Film',              description: 'Feature films — from landmark disability cinema to authentic contemporary storytelling.' },
  { id: 'talks-lectures',   channel: '07', call: 'TALK', title: 'Talks & Lectures',            description: 'TED talks, conference presentations, and lectures by disabled artists and scholars. All free.' },
  { id: 'festival-recent',  channel: '08', call: 'FEST', title: 'Festival & Recent Releases',  description: 'Films from disability-focused festivals and recent award circuit selections worth tracking.' },
];

export const CINEMA_ITEMS: CinemaItem[] = [

  // ── Documentaries ────────────────────────────────────────────────────────────

  {
    slug: 'crip-camp',
    title: 'Crip Camp: A Disability Revolution',
    director: 'James LeBrecht & Nicole Newnham',
    year: 2020,
    description: 'The documentary that changed everything for a generation of disability rights awareness. Starting at Camp Jened — a scrappy camp for disabled teens in the Catskills — it follows the activists who became the architects of the disability rights movement, including Judy Heumann and the 1977 San Francisco 504 Sit-In. Executive produced by Barack and Michelle Obama. Oscar-nominated. An absolute must-watch. Directed in part by James LeBrecht, a disabled director who attended the camp.',
    type: 'documentary',
    category: 'documentaries',
    tags: ['Disabled Voice', 'Disability History', 'Disability Justice'],
    isFree: false,
    platform: ['Netflix'],
    howToAccess: 'Available on Netflix (subscription required). Check your local public library — many offer free access to streaming services through Kanopy or similar programs.',
    isEssential: true,
    runtimeMinutes: 108,
    hasCaptions: true,
    hasAD: true,
  },
  {
    slug: 'lives-worth-living',
    title: 'Lives Worth Living',
    director: 'Eric Neudel',
    year: 2011,
    description: 'The PBS documentary tracing the history of the American disability rights movement from the 1940s through the passage of the ADA in 1990. Features first-person testimony from key organizers including Judy Heumann, Ed Roberts, and others who led the fight. Essential context for understanding how and why the ADA exists — told by the people who built it. Free to stream through PBS.',
    url: 'https://www.pbs.org/independentlens/documentaries/lives-worth-living/',
    type: 'documentary',
    category: 'documentaries',
    tags: ['Disability History', 'Disabled Voice', 'Free'],
    isFree: true,
    platform: ['PBS'],
    runtimeMinutes: 56,
    hasCaptions: true,
    isEssential: true,
  },
  {
    slug: 'through-deaf-eyes',
    title: 'Through Deaf Eyes',
    director: 'Lawrence Hott & Diane Garey',
    year: 2007,
    description: 'A sweeping two-hour PBS documentary on 200 years of Deaf American history and culture — from the founding of the American School for the Deaf in 1817 through Deaf President Now at Gallaudet in 1988 and beyond. Narrated by deaf and hard of hearing people; structured as cultural history, not as a medical story. The companion volume (edited by Brenda Jo Brueggemann) is available from Gallaudet University Press.',
    type: 'documentary',
    category: 'documentaries',
    tags: ['Deaf Culture', 'Disability History'],
    isFree: false,
    platform: ['PBS', 'Library'],
    howToAccess: 'Check PBS.org for current free availability. Available for borrowing through many public libraries; also available from Gallaudet University Press and on major streaming rental platforms.',
    runtimeMinutes: 120,
    hasCaptions: true,
  },
  {
    slug: 'sound-and-fury',
    title: 'Sound and Fury',
    director: 'Josh Aronson',
    year: 2000,
    description: 'An Oscar-nominated documentary following a Deaf family in which two brothers — one Deaf, one hearing — must each decide whether to give their young children cochlear implants. One of the most morally complex and culturally important documentaries in Deaf history. Illustrates the depth of the Deaf community\'s attachment to Deaf identity and ASL culture, and the devastating effects of decisions made without Deaf community input. Required viewing before forming opinions about cochlear implants.',
    type: 'documentary',
    category: 'documentaries',
    tags: ['Deaf Culture', 'Disabled Voice'],
    isFree: false,
    platform: ['Rent/Buy', 'Library'],
    howToAccess: 'Available to rent or purchase on Amazon, Apple TV, and similar platforms. Many public libraries own the DVD or a digital lending copy — check Kanopy.',
    runtimeMinutes: 80,
    hasCaptions: true,
    isEssential: true,
  },
  {
    slug: 'sins-invalid-unashamed-claim',
    title: 'Sins Invalid: An Unashamed Claim to Beauty',
    director: 'Sins Invalid',
    year: 2016,
    description: 'Documentary capturing the live performance event that has defined disability justice arts for two decades. Sins Invalid is a disability justice performance project centering disabled artists of color, queer and trans disabled artists, and the full, complex spectrum of disabled embodiment. The film documents performances from 2013 and earlier — and the interviews between acts are as important as the performances themselves. This is what access-centered art looks and sounds like in practice.',
    type: 'documentary',
    category: 'documentaries',
    tags: ['Disabled Voice', 'Disability Justice', 'Performance'],
    isFree: false,
    platform: ['Vimeo', 'Rent/Buy'],
    howToAccess: 'Available to rent through Vimeo On Demand at vimeo.com/sinsinvalid. Also sometimes screened at disability arts events and festivals — check sinsinvalid.org for upcoming community screenings.',
    isEssential: true,
    runtimeMinutes: 72,
  },
  {
    slug: 'far-from-the-tree',
    title: 'Far from the Tree',
    director: 'Rachel Dretzin',
    year: 2017,
    description: 'Based on Andrew Solomon\'s landmark book — a documentary following parents of children who are different from them in profound ways: a Deaf child, a child with Down syndrome, a child with autism, a child born with dwarfism. Beautifully made and genuinely complex; it neither sentimentalizes disability nor erases disability identity. The families portrayed are given real depth. One of the most accessible entry points to disability culture and identity for a general audience.',
    type: 'documentary',
    category: 'documentaries',
    tags: ['Deaf Culture', 'Disability Identity'],
    isFree: false,
    platform: ['Hulu', 'Rent/Buy'],
    howToAccess: 'Available on Hulu and to rent or purchase on streaming platforms.',
    runtimeMinutes: 93,
    hasCaptions: true,
  },

  // ── Performance & Dance ──────────────────────────────────────────────────────

  {
    slug: 'axis-dance-company-recordings',
    title: 'AXIS Dance Company — Free Video Archive',
    creator: 'AXIS Dance Company',
    description: 'AXIS Dance Company (Oakland, CA) — one of the longest-running integrated dance companies in the world, integrating wheelchair users and standing dancers — posts full performances, excerpts, and process videos freely on YouTube. Their work doesn\'t just "include" disabled dancers; the artistic vocabulary of integrated movement is the whole point. Search "AXIS Dance Company" on YouTube for their full freely available archive.',
    url: 'https://www.youtube.com/@axisdancecompany',
    type: 'performance-recording',
    category: 'performance',
    tags: ['Disabled Voice', 'Disability Arts', 'Free', 'Dance'],
    isFree: true,
    platform: ['YouTube'],
    hasCaptions: true,
    isEssential: true,
  },
  {
    slug: 'kinetic-light-wired',
    title: 'Kinetic Light — Performance Films',
    creator: 'Kinetic Light (Alice Sheppard & Laurel Lawson)',
    year: 2019,
    description: 'Kinetic Light is a disability-led performance company whose work in dance, technology, and access has redefined what both of those terms mean. Their Audimance® platform — which lets audience members choose from multiple audio tracks during live performance — is one of the most innovative audio description frameworks ever created. Many excerpts and full performances are freely available on their website and Vimeo. WIRED (2019) remains their landmark work.',
    url: 'https://kineticlight.org/wired',
    type: 'performance-recording',
    category: 'performance',
    tags: ['Disabled Voice', 'Disability Arts', 'Free', 'Dance', 'Audio Description'],
    isFree: true,
    platform: ['Vimeo', 'Web'],
  },
  {
    slug: 'deaf-west-spring-awakening',
    title: 'Deaf West Theatre: Spring Awakening',
    creator: 'Deaf West Theatre',
    year: 2015,
    description: 'The 2015 Deaf West production of Spring Awakening on Broadway — performed simultaneously in ASL and English, with deaf and hearing actors fully integrated — was a landmark in American theater. The full production is not freely available, but multiple excerpts, Tony Award performances, and behind-the-scenes footage are free on YouTube. This is what bilingual, bicultural theater looks like when access is the artistic vision, not an add-on.',
    type: 'performance-recording',
    category: 'performance',
    tags: ['Deaf Culture', 'Disability Arts', 'Theater'],
    isFree: false,
    platform: ['YouTube (excerpts)', 'Library'],
    howToAccess: 'Full production recording not commercially available. Extensive excerpts and performances on YouTube — search "Deaf West Spring Awakening Tony Awards." The cast recording is available on streaming audio platforms.',
  },
  {
    slug: 'graeae-theatre-recordings',
    title: 'Graeae Theatre Company — Archive & Recordings',
    creator: 'Graeae Theatre Company (UK)',
    description: 'Graeae is the UK\'s leading disabled-led theater company — founded in 1980, led by Jenny Sealey, co-director of the 2012 Paralympic Opening Ceremony. Their productions integrate access (BSL, audio description, captioning) as intrinsic elements of the artistic work, not technical afterthoughts. Selected recordings and excerpts available free via their website and on YouTube. Essential reference for integrated access as artistic practice.',
    url: 'https://graeae.org',
    type: 'performance-recording',
    category: 'performance',
    tags: ['Disabled Voice', 'Disability Arts', 'Free', 'International'],
    isFree: true,
    platform: ['YouTube', 'Web'],
  },

  // ── Short Films & Video Art ──────────────────────────────────────────────────

  {
    slug: 'disability-film-challenge-winners',
    title: 'Disability Film Challenge — Annual Winners',
    creator: 'Easterseals Disability Film Challenge',
    description: 'Each year, the Easterseals Disability Film Challenge releases winning short films on YouTube — all made within a 55-hour filmmaking window, all featuring disabled talent in front of and behind the camera. The result is a growing free archive of authentic short disability filmmaking. Films range from comedy to drama to documentary. An incredible resource for studying authentic disability representation alongside emerging disabled filmmakers.',
    url: 'https://www.youtube.com/@disabilityfilmchallenge',
    type: 'short-film',
    category: 'short-film',
    tags: ['Disabled Voice', 'Disability Arts', 'Free'],
    isFree: true,
    platform: ['YouTube'],
    hasCaptions: true,
  },
  {
    slug: 'disability-visibility-project-films',
    title: 'Disability Visibility Project — Film & Video Archive',
    creator: 'Disability Visibility Project (Alice Wong)',
    description: 'Alice Wong\'s Disability Visibility Project maintains a growing archive of short films, video essays, recorded readings, and multimedia pieces — all freely available, most captioned. Includes her own on-camera work, community-produced films, and curated media. A perfect accompaniment to the DVP podcast and anthology.',
    url: 'https://disabilityvisibilityproject.com/read-watch-listen/',
    type: 'short-film',
    category: 'short-film',
    tags: ['Disabled Voice', 'Free'],
    isFree: true,
    platform: ['Web', 'YouTube'],
    hasCaptions: true,
  },
  {
    slug: 'superfest-online-archive',
    title: 'Superfest International Disability Film Festival — Online Archive',
    creator: 'Superfest (Berkeley/UCSF)',
    description: 'Superfest is the world\'s longest-running disability film festival, and it makes selected past films available for free online streaming. Every film in the Superfest archive has been screened with open captions and audio description. This is the most accessible film festival archive in existence — and a portal to disability filmmaking from around the world. Check their website for what is currently freely available.',
    url: 'https://superfestfilm.com',
    type: 'short-film',
    category: 'short-film',
    tags: ['Disabled Voice', 'Disability Arts', 'Free', 'International'],
    isFree: true,
    platform: ['Web'],
    hasCaptions: true,
    hasAD: true,
  },
  {
    slug: 'disabilityarts-tv',
    title: 'DisabilityArts.TV — Online Film Platform (UK)',
    creator: 'Disability Arts Online (UK)',
    description: 'A free UK-based online platform dedicated to disability arts film and video — short films, documentation of live work, artist interviews, and experimental video art. Disability Arts Online is the leading UK platform for disability arts criticism and culture; DisabilityArts.TV is their film arm. Captioned content throughout. Essential for international disability arts perspective.',
    url: 'https://disabilityartsonline.org.uk/disability-arts-film',
    type: 'short-film',
    category: 'short-film',
    tags: ['Disabled Voice', 'Disability Arts', 'Free', 'International'],
    isFree: true,
    platform: ['Web'],
    hasCaptions: true,
  },

  // ── Podcasts ─────────────────────────────────────────────────────────────────

  {
    slug: 'disability-visibility-project-podcast',
    title: 'Disability Visibility Project',
    creator: 'Alice Wong',
    description: 'The essential disability culture podcast. Alice Wong interviews disabled activists, artists, writers, musicians, and community organizers — centering voices that are rarely centered elsewhere. The archive spans hundreds of episodes across all disability communities. Transcripts provided for every episode. Required listening for anyone entering this field.',
    url: 'https://disabilityvisibilityproject.com/podcasts/',
    type: 'podcast',
    category: 'podcasts',
    tags: ['Disabled Voice', 'Disability Justice', 'Free'],
    isFree: true,
    platform: ['Podcast', 'Web'],
    hasCaptions: true,
    isEssential: true,
  },
  {
    slug: 'reid-my-mind-radio',
    title: 'Reid My Mind Radio',
    creator: 'Thomas Reid',
    description: 'Thomas Reid — blind audio describer, narrator, and storyteller — produces one of the most artfully crafted disability podcasts. Reid My Mind Radio covers blindness, audio description craft, disability culture, and Black disability experience. Reid is both a practitioner (he wrote the AD for Joybubbles, the first Sundance film with open audio description) and a public educator. His AD training episodes are among the best free resources for aspiring audio describers. Full transcripts available.',
    url: 'https://reidmymind.com',
    type: 'podcast',
    category: 'podcasts',
    tags: ['Disabled Voice', 'Audio Description', 'Free'],
    isFree: true,
    platform: ['Podcast', 'Web'],
    isEssential: true,
  },
  {
    slug: 'the-accessible-stall',
    title: 'The Accessible Stall',
    creator: 'Emily Ladau & Kyle Khachadurian',
    description: 'A candid, often funny, and always sharp podcast about disability culture, identity, and the everyday experience of being disabled in America. Emily Ladau and Kyle Khachadurian cover everything from ableism in pop culture to accessibility in travel to disability pride politics. One of the most widely listened disability podcasts among younger disabled audiences.',
    url: 'https://www.theaccessiblestall.com',
    type: 'podcast',
    category: 'podcasts',
    tags: ['Disabled Voice', 'Free'],
    isFree: true,
    platform: ['Podcast', 'Web'],
  },
  {
    slug: 'disability-after-dark',
    title: 'Disability After Dark',
    creator: 'Andrew Gurza',
    description: 'Andrew Gurza\'s long-running podcast at the explicit intersection of disability and queerness — sexuality, dating, intimacy, and identity as a disabled gay man. Gurza goes where very few disability podcasts go: the sexual lives, desires, and experiences of disabled people as worthy of celebration, not just acknowledgment. Essential for understanding the full human experience of disability — not just professional practice.',
    url: 'https://disabilityafterdark.com',
    type: 'podcast',
    category: 'podcasts',
    tags: ['Disabled Voice', 'Free', 'LGBTQ+'],
    isFree: true,
    platform: ['Podcast', 'Web'],
  },
  {
    slug: 'krip-hop-nation-podcast',
    title: 'Krip-Hop Nation Radio & Podcast',
    creator: 'Leroy F. Moore Jr.',
    description: 'Leroy F. Moore Jr. is the founder of Krip-Hop Nation — a platform and movement celebrating hip-hop artists with disabilities. The Krip-Hop Nation podcast and radio show connects disability culture with hip-hop history, Black disability culture, and the stories of disabled musicians who are consistently erased from mainstream music history. Centering Black disabled artistry, free to stream.',
    url: 'https://kriphopnation.com',
    type: 'podcast',
    category: 'podcasts',
    tags: ['Disabled Voice', 'Disability Justice', 'Free', 'Music'],
    isFree: true,
    platform: ['Podcast', 'Web'],
  },
  {
    slug: 'the-war-on-wheels-podcast',
    title: 'The War on Wheels',
    creator: 'Dominick Evans',
    description: 'Dominick Evans — disabled filmmaker and activist — hosts this podcast covering disability representation in media: film, TV, and social media. Episodes cover authentic casting, cripping up, disability tropes, and what it means to have creative control over your own story. Particularly strong on the intersection of disability and race in media representation.',
    url: 'https://dominickevans.com/the-war-on-wheels-podcast/',
    type: 'podcast',
    category: 'podcasts',
    tags: ['Disabled Voice', 'Film', 'Representation', 'Free'],
    isFree: true,
    platform: ['Podcast', 'Web'],
  },

  // ── Series & Television ──────────────────────────────────────────────────────

  {
    slug: 'speechless',
    title: 'Speechless',
    creator: 'Scott Silveri',
    year: 2016,
    description: 'Three seasons (ABC, 2016–2019) of a sitcom centering JJ DiMeo — a teenager with cerebral palsy — and the family chaos of being JJ\'s family. Played by Micah Fowler, who has cerebral palsy himself. Remarkable for using AAC (augmentative and alternative communication) as the actual comic mechanism — JJ\'s aide Kenneth speaks his words, creating layered, physical comedy. One of very few mainstream sitcoms to cast a disabled actor in the disabled lead role. Smart, funny, and warm.',
    type: 'series',
    category: 'series-tv',
    tags: ['Disabled Voice', 'Disability Representation'],
    isFree: false,
    platform: ['Hulu', 'Disney+', 'Rent/Buy'],
    howToAccess: 'Available on Hulu (subscription). May be available through your library\'s digital lending service. Individual episodes rentable on Amazon and Apple TV.',
    isEssential: true,
    hasCaptions: true,
  },
  {
    slug: 'deaf-u',
    title: 'Deaf U',
    creator: 'Nyle DiMarco (exec. producer)',
    year: 2020,
    description: 'A Netflix docu-series following Deaf and hard of hearing students at Gallaudet University in Washington, DC — the world\'s only university designed for Deaf students. Follows the social lives, relationships, community politics, and identity negotiations of young Deaf adults. Controversial within the Deaf community (some felt it amplified certain voices over others), but a genuine and rare window into Deaf campus life and the diversity of Deaf identity. Subtitles carry ASL conversations into English.',
    type: 'series',
    category: 'series-tv',
    tags: ['Deaf Culture', 'Disabled Voice'],
    isFree: false,
    platform: ['Netflix'],
    howToAccess: 'Available on Netflix (subscription required).',
    hasCaptions: true,
  },
  {
    slug: 'special-netflix',
    title: 'Special',
    creator: 'Ryan O\'Connell',
    year: 2019,
    description: 'Ryan O\'Connell — a disabled, gay writer — created, wrote, and stars in this semi-autobiographical Netflix comedy about a young man with cerebral palsy navigating early adulthood, queerness, disability identity, and the decision of whether to disclose his disability. Two seasons. Sharp, funny, and genuinely self-aware about disability politics in a way that most mainstream TV never achieves. One of the best pieces of disabled self-representation in television history.',
    type: 'series',
    category: 'series-tv',
    tags: ['Disabled Voice', 'LGBTQ+'],
    isFree: false,
    platform: ['Netflix'],
    howToAccess: 'Available on Netflix (subscription required).',
    isEssential: true,
    hasCaptions: true,
  },
  {
    slug: 'the-a-word',
    title: 'The A Word',
    creator: 'Peter Bowker (UK) / Bradford Anderson (US adaptation)',
    year: 2016,
    description: 'A BBC/Sky series (adapted from the Israeli series Yellow Peppers) following a family coming to understand that their young son is autistic. The British original — available in the US — is widely praised for its authentic portrayal of autistic experience and the complexity of family dynamics around late diagnosis. The child at the center (played by non-autistic child actor Max Vento) has generated debate, but the writing around what autism means and doesn\'t mean is unusually thoughtful for mainstream TV.',
    type: 'series',
    category: 'series-tv',
    tags: ['Disability Representation', 'Neurodivergent'],
    isFree: false,
    platform: ['Peacock', 'Acorn TV', 'Rent/Buy'],
    howToAccess: 'Available on Acorn TV and Peacock; also available to rent/purchase on streaming platforms.',
    hasCaptions: true,
  },

  // ── Narrative Film ───────────────────────────────────────────────────────────

  {
    slug: 'children-of-a-lesser-god',
    title: 'Children of a Lesser God',
    director: 'Randa Haines',
    year: 1986,
    description: 'Marlee Matlin\'s Oscar-winning performance as a deaf woman in a relationship with a hearing speech therapist who fails to see her on her own terms. Complex — the film\'s framing reflects its era, and its ending is contested. But Matlin\'s performance, the centrality of ASL, and the frank depiction of Deaf-hearing power dynamics make it required viewing for understanding how mainstream cinema has engaged with Deaf identity. Matlin remains the only deaf actress to have won the Academy Award.',
    type: 'film',
    category: 'narrative-film',
    tags: ['Deaf Culture', 'Disability Representation'],
    isFree: false,
    platform: ['Rent/Buy', 'Library'],
    howToAccess: 'Available to rent or purchase on most digital streaming platforms. Available on DVD through many public libraries.',
    runtimeMinutes: 119,
    hasCaptions: true,
    isEssential: true,
  },
  {
    slug: 'the-diving-bell-and-the-butterfly',
    title: 'The Diving Bell and the Butterfly',
    director: 'Julian Schnabel',
    year: 2007,
    description: 'Based on Jean-Dominique Bauby\'s memoir, written by blinking his left eye — the only movement possible after a brainstem stroke left him with locked-in syndrome. Schnabel puts the camera behind Bauby\'s eye for the film\'s first act, putting the viewer in locked-in consciousness in a way that\'s unlike any other film. Beautiful, devastating, and formally inventive. Raises complex questions about narrative control of disabled lives in cinema — worth watching critically alongside disability studies scholarship.',
    type: 'film',
    category: 'narrative-film',
    tags: ['Disability Representation', 'International'],
    isFree: false,
    platform: ['Rent/Buy', 'Library'],
    howToAccess: 'Available to rent or purchase on Amazon, Apple TV, and similar platforms. Available on DVD through many public libraries.',
    runtimeMinutes: 112,
    hasCaptions: true,
  },
  {
    slug: 'keep-the-change',
    title: 'Keep the Change',
    director: 'Rachel Israel',
    year: 2017,
    description: 'A love story between two autistic adults — played by autistic actors Brandon Polansky and Samantha Elisofon — who meet in a social skills program in New York City. Remarkable for being one of the only mainstream narrative films in which autistic characters are played by autistic actors and in which the emotional stakes are genuinely theirs, not their neurotypical families\'. Low-key, funny, and deeply human. Won the Audience Award at the Tribeca Film Festival.',
    type: 'film',
    category: 'narrative-film',
    tags: ['Disabled Voice', 'Disability Representation', 'Neurodivergent'],
    isFree: false,
    platform: ['Rent/Buy'],
    howToAccess: 'Available to rent or purchase on Amazon, Apple TV, and similar platforms.',
    runtimeMinutes: 94,
    isEssential: true,
  },
  {
    slug: 'sound-of-metal',
    title: 'Sound of Metal',
    director: 'Darius Marder',
    year: 2019,
    description: 'A heavy metal drummer loses his hearing rapidly and must reckon with what that loss means — for his sense of self, his relationship, his music, and his life. Won the Academy Award for Sound and Film Editing. The sound design is transformative — the film lets you hear through Ruben\'s changing ears. The Deaf community\'s response is worth reading alongside the film: some praise it, others critique it for centering hearing loss as tragedy. Paul Raci, who plays Ruben\'s mentor, is a CODA (Child of Deaf Adults) and CART user himself.',
    type: 'film',
    category: 'narrative-film',
    tags: ['Deaf Culture', 'Disability Representation'],
    isFree: false,
    platform: ['Amazon Prime'],
    howToAccess: 'Available on Amazon Prime Video (subscription) and to rent/purchase on other platforms.',
    runtimeMinutes: 130,
    hasCaptions: true,
    hasAD: true,
  },
  {
    slug: 'coda-2021',
    title: 'CODA',
    director: 'Siân Heder',
    year: 2021,
    description: 'Best Picture winner at the 2022 Academy Awards. A hearing child of Deaf adults (Ruby) navigates her hearing identity, her family\'s fishing business, and her ambitions as a singer. Three of the four family roles played by Deaf or hard of hearing actors (Marlee Matlin, Troy Kotsur, Daniel Durant). Kotsur won Best Supporting Actor — the first Deaf actor to win that award. The Deaf community\'s reaction is complex and worth reading: real representation, real Deaf actors, but the narrative remains centered on the hearing character\'s journey away from her Deaf family.',
    type: 'film',
    category: 'narrative-film',
    tags: ['Deaf Culture', 'Disabled Voice'],
    isFree: false,
    platform: ['Apple TV+'],
    howToAccess: 'Available on Apple TV+ (subscription). Available to rent/purchase on other streaming platforms.',
    runtimeMinutes: 112,
    hasCaptions: true,
    hasAD: true,
  },

  // ── Talks & Lectures ─────────────────────────────────────────────────────────

  {
    slug: 'stella-young-not-your-inspiration',
    title: 'I\'m Not Your Inspiration, Thank You Very Much',
    creator: 'Stella Young',
    year: 2014,
    description: 'The most-watched disability culture talk in TED history — Stella Young, a disabled comedian and editor of Ramp Up (ABC Australia\'s disability affairs site), delivers the definitive 9-minute critique of inspiration porn: the objectification of disabled people for the emotional benefit of non-disabled people. She names the structure clearly, illustrates it with precision, and does it all with a warm sense of humor. Required viewing for anyone using images of disabled people in any context. Full transcript available.',
    url: 'https://www.ted.com/talks/stella_young_i_m_not_your_inspiration_thank_you_very_much',
    type: 'talk',
    category: 'talks-lectures',
    tags: ['Disabled Voice', 'Free'],
    isFree: true,
    platform: ['TED', 'YouTube'],
    runtimeMinutes: 9,
    hasCaptions: true,
    isEssential: true,
  },
  {
    slug: 'haben-girma-accessibility-law',
    title: 'Haben Girma: How Accessibility Leads to Equality',
    creator: 'Haben Girma',
    year: 2018,
    description: 'DeafBlind disability rights lawyer Haben Girma makes the case that accessibility is not charity — it\'s civil rights, and it creates opportunity for everyone. One of the most effective accessible talks about accessibility: the irony of Girma delivering it via braille display and sip-and-puff communications technology is entirely the point. Full transcript on TED.com.',
    url: 'https://www.ted.com/talks/haben_girma_how_accessibility_leads_to_equality',
    type: 'talk',
    category: 'talks-lectures',
    tags: ['Disabled Voice', 'Free'],
    isFree: true,
    platform: ['TED'],
    runtimeMinutes: 13,
    hasCaptions: true,
  },
  {
    slug: 'judy-heumann-disability-rights',
    title: 'Our Fight for Disability Rights — and Why We\'re Not Done Yet',
    creator: 'Judith Heumann',
    year: 2016,
    description: 'Judith Heumann — arguably the most important disability rights activist in American history, architect of the 504 Sit-In, key drafter of the IDEA and ADA — delivers a full account of how she became an organizer and why the fight continues. Essential alongside Crip Camp and her memoir Being Heumann. Given in 2016, it covers both history and then-current threats. Full transcript on TED.com.',
    url: 'https://www.ted.com/talks/judith_heumann_our_fight_for_disability_rights_and_why_we_re_not_done_yet',
    type: 'talk',
    category: 'talks-lectures',
    tags: ['Disabled Voice', 'Disability History', 'Free'],
    isFree: true,
    platform: ['TED'],
    runtimeMinutes: 15,
    hasCaptions: true,
  },
  {
    slug: 'alice-wong-disability-visibility-talks',
    title: 'Alice Wong — Talks & Recorded Lectures',
    creator: 'Alice Wong',
    description: 'Alice Wong\'s recorded talks — at conferences, universities, and festivals — are collected and linked through the Disability Visibility Project website. She speaks on disability identity, ableism in healthcare, disability media representation, and the labor of disabled activists. Many are freely available with transcripts. Start with the DVP website\'s Listen section for a curated collection.',
    url: 'https://disabilityvisibilityproject.com/read-watch-listen/',
    type: 'talk',
    category: 'talks-lectures',
    tags: ['Disabled Voice', 'Disability Justice', 'Free'],
    isFree: true,
    platform: ['Web', 'YouTube'],
    hasCaptions: true,
  },
  {
    slug: 'thomas-reid-audio-description-demo',
    title: 'Thomas Reid — Audio Description Training Talks',
    creator: 'Thomas Reid',
    description: 'Thomas Reid — blind narrator, audio describer, and host of Reid My Mind Radio — has delivered public talks and training sessions on audio description craft that are available free online. His talks on objectivity, identity description, and the aesthetics of description are among the most practically useful free resources for practicing and aspiring audio describers. Check his website (reidmymind.com) and YouTube for current available recordings.',
    url: 'https://reidmymind.com',
    type: 'talk',
    category: 'talks-lectures',
    tags: ['Disabled Voice', 'Audio Description', 'Free'],
    isFree: true,
    platform: ['YouTube', 'Web'],
    hasCaptions: true,
  },

  // ── Festival & Recent Releases ────────────────────────────────────────────────

  {
    slug: 'joybubbles-2026',
    title: 'Joybubbles',
    director: 'Rachael J. Morrison',
    year: 2026,
    description: 'A documentary portrait of Joe Engressia, born blind, who became one of the first phone phreaks — able to whistle precise tones that let him navigate the telephone network before the digital era. Made its world premiere at Sundance 2026, where it became the first film in Sundance history to be screened with open audio description — the AD track played aloud in the theater alongside open captions. Audio description written by Cheryl Green and narrated by Thomas Reid, with blind script editor Rick Hammond. A landmark in disability arts accessibility.',
    type: 'documentary',
    category: 'festival-recent',
    tags: ['Disabled Voice', 'Disability Arts', 'Audio Description'],
    isFree: false,
    platform: ['Festival Circuit'],
    howToAccess: 'Currently in festival distribution following its Sundance 2026 premiere. Watch for streaming announcement — its accessibility milestone (first open AD at Sundance) means the accessibility community is tracking this closely.',
    hasAD: true,
    hasCaptions: true,
  },
  {
    slug: 'disposable-humanity-2026',
    title: 'Disposable Humanity',
    director: 'Cameron S. Mitchell',
    year: 2026,
    description: 'Centerpiece film at ReelAbilities New York 2026. Investigates the Nazi Aktion T4 program — which systematically killed an estimated 200,000–300,000 disabled people beginning in 1939, before the broader Holocaust machinery was deployed. An essential and underknown history: the first victims of the Nazi genocide were disabled people, and that chapter of history has been systematically erased from mainstream Holocaust education. Critically important for disability rights and Holocaust memory.',
    type: 'documentary',
    category: 'festival-recent',
    tags: ['Disability History'],
    isFree: false,
    platform: ['Festival Circuit'],
    howToAccess: 'Screened at ReelAbilities New York 2026. Watch for streaming and distribution announcements at reelabilities.org.',
  },
  {
    slug: 'viktor-deaf-man-war-2026',
    title: 'VIKTOR — A Deaf Man in a War He Cannot Hear',
    director: 'Olivier Sarbila',
    year: 2026,
    description: 'Portrait of a Deaf Ukrainian man navigating the Russian invasion of Ukraine. Screened at ReelAbilities New York 2026. A powerful intersection of Deaf identity, war, and the particular experience of navigating conflict without hearing — air raid sirens, voices, commands. One of the most urgent films at ReelAbilities 2026.',
    type: 'documentary',
    category: 'festival-recent',
    tags: ['Deaf Culture', 'Disabled Voice', 'International'],
    isFree: false,
    platform: ['Festival Circuit'],
    howToAccess: 'Currently in festival distribution. Watch for streaming announcements at reelabilities.org.',
  },
  {
    slug: 'reelabilities-curated-series',
    title: 'ReelAbilities Film Festival — Curated Archive',
    creator: 'ReelAbilities Film Festival',
    description: 'ReelAbilities — now in 20+ cities across the US — curates the best in disability-focused filmmaking each year and maintains an online archive of past programming. Their website (reelabilities.org) links to films that have received digital distribution from past festivals, and their programming is the best single annual guide to what\'s worth watching in disability cinema. Sign up for their newsletter for the most current accessible options.',
    url: 'https://reelabilities.org',
    type: 'documentary',
    category: 'festival-recent',
    tags: ['Disability Arts', 'Free (selected)'],
    isFree: false,
    platform: ['Web'],
    howToAccess: 'Visit reelabilities.org for current programming and links to films available for online streaming. Festival screenings run annually in cities including New York, Los Angeles, Cleveland, Houston, and more.',
  },
];

// ── Lookup helpers ──────────────────────────────────────────────────────────────

export const CINEMA_ITEM_BY_SLUG: Record<string, CinemaItem> =
  Object.fromEntries(CINEMA_ITEMS.map((item) => [item.slug, item]));

export const CINEMA_CATEGORY_BY_ID: Record<string, CinemaCategory> =
  Object.fromEntries(CINEMA_CATEGORIES.map((cat) => [cat.id, cat]));

export const FREE_CINEMA_ITEMS = CINEMA_ITEMS.filter((i) => i.isFree);
export const ESSENTIAL_CINEMA_ITEMS = CINEMA_ITEMS.filter((i) => i.isEssential);
